"use client"

import { useEffect, useState } from "react"

import AuthForm from "@/components/authentication/AuthForm"
import { BackgroundImage } from "@/components/authentication/background-image"
import { getRandomNumber } from "@/lib/utils"

export const Content = () => {
  const [imageUrl, setImageUrl] = useState("")
  const [referrerId, setReferrerId] = useState("")

  useEffect(() => {
    if (typeof window !== "undefined") {
      const pathname = window.location.href
      const url = new URL(pathname)
      const referrerId = url.searchParams.get("referrer") || ""
      localStorage.setItem("referrerId", referrerId)
      setReferrerId(referrerId)
    }

    const imageId = getRandomNumber(1, 10)
    setImageUrl(`/img/image${imageId}.webp`)
  }, [])

  return (
    <div className="dark">
      <BackgroundImage imageUrl={imageUrl} />
      <div className="fixed left-1/2 top-1/2 flex h-[calc(100vh-6rem)] w-[calc(100vw-6rem)] -translate-x-1/2 -translate-y-1/2 transform overflow-hidden rounded-lg">
        <div className="absolute flex h-full w-[30rem] items-start justify-center bg-background">
          <AuthForm />
        </div>
        {imageUrl && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={imageUrl}
            className="absolute right-0 h-full w-[calc(100%-30rem)] object-cover"
            alt={"Background generated by AI"}
          />
        )}
      </div>
    </div>
  )
}
