import { Tour } from "onborda/dist/types"

export const tours: Tour[] = [
  {
    tour: "firsttour",
    steps: [
      {
        icon: <>👋</>,
        title: "Tour 1, Step 1",
        content: (
          <>
            Voici le toggle qui contient la déconnexion, le settings, le profile
          </>
        ),
        selector: "#tour1-step1",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🪄</>,
        title: "Tour 1, Step 2",
        content: <>First tour, second step</>,
        selector: "#tour1-step2",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🎩</>,
        title: "Tour 1, Step 3",
        content: <>First tour, third step</>,
        selector: "#tour1-step3",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀</>,
        title: "Tour 1, Step 4",
        content: <>First tour, fourth step</>,
        selector: "#tour1-step4",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀</>,
        title: "Tour 1, Step 5",
        content: <>First tour, fifth step</>,
        selector: "#tour1-step5",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🎩</>,
        title: "Tour 1, Step 3",
        content: <>First tour, third step</>,
        selector: "#tour1-step6",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀</>,
        title: "Tour 1, Step 4",
        content: <>First tour, fourth step</>,
        selector: "#tour1-step7",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀</>,
        title: "Tour 1, Step 5",
        content: <>First tour, fifth step</>,
        selector: "#tour1-step8",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
    ],
  },
  {
    tour: "secondtour",
    steps: [
      {
        icon: <>👋👋</>,
        title: "Second tour, Step 1",
        content: <>Second tour, first step!</>,
        selector: "#tour2-step1",
        side: "bottom-left",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🪄🪄</>,
        title: "Second tour, Step 2",
        content: <>Second tour, second step!</>,
        selector: "#tour2-step2",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🎩🎩</>,
        title: "Second tour, Step 3",
        content: <>Second tour, third step!</>,
        selector: "#tour2-step3",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀🚀</>,
        title: "Second tour, Step 4",
        content: <>Second tour, fourth step!</>,
        selector: "#tour2-step4",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🚀🚀</>,
        title: "Second tour, Step 5",
        content: <>Second tour, fifth step!</>,
        selector: "#tour2-step5",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
    ],
  },
  {
    tour: "thirdtour",
    steps: [
      {
        icon: <>👋👋👋</>,
        title: "Third tour, Step 1",
        content: <>Third tour, first step!</>,
        selector: "#tour3-step1",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🪄🪄🪄</>,
        title: "Third tour, Step 2",
        content: <>Third tour, second step!</>,
        selector: "#tour3-step2",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      {
        icon: <>🪄🪄🪄</>,
        title: "Third tour, Step 3",
        content: <>Third tour, third step!</>,
        selector: "#tour3-step3",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
    ],
  },
  {
    tour: "fourthtour",
    steps: [
      {
        icon: <>👋👋👋👋</>,
        title: "Fourth tour, Step 1",
        content: <>Fourth tour, first step!</>,
        selector: "#tour4-step1",
        side: "bottom-right",
        showControls: true,
        pointerPadding: 12,
        pointerRadius: 12,
      },
      // {
      //   icon: <>🪄🪄🪄🪄</>,
      //   title: "Fourth tour, Step 2",
      //   content: <>Fourth tour, second step!</>,
      //   selector: "#tour4-step2",
      //   side: "bottom-right",
      //   showControls: true,
      //   pointerPadding: 12,
      //   pointerRadius: 12,
      // },
      // {
      //   icon: <>🪄🪄🪄🪄</>,
      //   title: "Fourth tour, Step 2",
      //   content: <>Fourth tour, third step!</>,
      //   selector: "#tour4-step3",
      //   side: "bottom-right",
      //   showControls: true,
      //   pointerPadding: 12,
      //   pointerRadius: 12,
      // },
    ],
  },
]
